"""Initial schema; frozen at revision 0001."""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onboarding_cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("owner_id", sa.String(length=100), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("missing_fields", sa.JSON(), nullable=False),
        sa.Column("conversation_id", sa.String(length=200), nullable=True),
        sa.Column("employee_id", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id"),
    )
    op.create_index(op.f("ix_onboarding_cases_owner_id"), "onboarding_cases", ["owner_id"], unique=False)
    op.create_index(op.f("ix_onboarding_cases_tenant_id"), "onboarding_cases", ["tenant_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["onboarding_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_tenant_id"), "audit_events", ["tenant_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("doc_type", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("scan_status", sa.String(length=30), nullable=False),
        sa.Column("extraction", sa.JSON(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["onboarding_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_case_id"), "documents", ["case_id"], unique=False)
    op.create_table(
        "employees",
        sa.Column("pan_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["onboarding_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id"),
        sa.UniqueConstraint("tenant_id", "pan_fingerprint"),
    )
    op.create_index(op.f("ix_employees_tenant_id"), "employees", ["tenant_id"], unique=False)
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("employee_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["onboarding_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "key"),
    )
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        tenant = "tenant_id = current_setting('app.tenant_id', true)"
        case_access = f"{tenant} AND (owner_id = current_setting('app.subject', true) OR current_setting('app.is_hr', true) = 'true')"
        for name in ("onboarding_cases", "documents", "employees", "idempotency_keys", "audit_events"):
            condition = (
                case_access
                if name == "onboarding_cases"
                else f"{tenant} AND EXISTS (SELECT 1 FROM onboarding_cases c WHERE c.id = {name}.case_id)"
            )
            op.execute(f'ALTER TABLE "{name}" ENABLE ROW LEVEL SECURITY')
            op.execute(f'ALTER TABLE "{name}" FORCE ROW LEVEL SECURITY')
            op.execute(
                f'CREATE POLICY scoped_access ON "{name}" USING ({condition}) WITH CHECK ({condition})'
            )


def downgrade():
    for name in ("idempotency_keys", "employees", "documents", "audit_events", "onboarding_cases"):
        op.drop_table(name)
